/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Financeiro;

import DAO.JBDCCadastroFinanceiro;
import DAO.JBDCCadastroImovel;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.plaf.basic.BasicButtonUI;
import Imóvel.Imovel;
import javax.swing.JOptionPane;
import Financeiro.Financeiro;
import Model.FinanceiroModel;
import java.util.ArrayList;

/**
 *
 * @author pedro
 */
public class CadastroFinanceiro extends javax.swing.JPanel {

    /**
     * Creates new form CadastroImovel
     */
    public CadastroFinanceiro() {
        initComponents();
        carregarIdsImoveis();
        JButton[] btns = {BtnCadastrar, BtnCancelar, BtnRetornar};
        for (JButton btn : btns) {
            btn.setBackground(new Color(30, 122, 206));
            btn.setUI(new BasicButtonUI());
            BtnRetornar.setBackground(Color.WHITE);
            btn.addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent e) {

                }

                @Override
                public void mousePressed(MouseEvent e) {

                }

                @Override
                public void mouseReleased(MouseEvent e) {

                }

                @Override
                public void mouseEntered(MouseEvent e) {
                    btn.setBackground(new Color(47, 141, 227));
                    BtnRetornar.setBackground(Color.WHITE);
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    btn.setBackground(new Color(30, 122, 206));
                    BtnRetornar.setBackground(Color.WHITE);
                }

            });
        }

    }   
    public void carregarIdsImoveis() {
    JBDCCadastroImovel imovelDAO = new JBDCCadastroImovel();
    ArrayList<Integer> idsImoveis = imovelDAO.buscarIdsImoveis();

    idimoveisFinanceiro.removeAllItems();

    for (Integer id : idsImoveis) {
        idimoveisFinanceiro.addItem(id.toString()); 
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelCentral = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        BtnCadastrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ValorTotalLabel = new javax.swing.JLabel();
        IdImovelLabel = new javax.swing.JLabel();
        SituacaoComboLabel = new javax.swing.JLabel();
        BtnCancelar = new javax.swing.JButton();
        BtnRetornar = new javax.swing.JButton();
        ValorTotal = new javax.swing.JTextField();
        ValorParcela = new javax.swing.JTextField();
        ValorParcelaLabel = new javax.swing.JLabel();
        NParcelas = new javax.swing.JTextField();
        NParcelasLabel = new javax.swing.JLabel();
        NomeLocador = new javax.swing.JTextField();
        NomeLocadorLabel = new javax.swing.JLabel();
        NomeLocatario = new javax.swing.JTextField();
        NomeLocatarioLabel = new javax.swing.JLabel();
        NomeContratoLabel1 = new javax.swing.JLabel();
        NomeContrato = new javax.swing.JTextField();
        idimoveisFinanceiro = new javax.swing.JComboBox<>();
        IdImovelLabel1 = new javax.swing.JLabel();
        nomeImovelFinanceiro = new javax.swing.JTextField();
        situacaoComboFinanceiro = new javax.swing.JComboBox<>();

        PainelCentral.setBackground(new java.awt.Color(36, 114, 221));
        PainelCentral.setForeground(new java.awt.Color(255, 255, 255));
        PainelCentral.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("/Home/Financeiro/Cadastrar");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Imobils, Sistema Imobiliário");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        BtnCadastrar.setBackground(new java.awt.Color(30, 122, 206));
        BtnCadastrar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        BtnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        BtnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Edit_1.png"))); // NOI18N
        BtnCadastrar.setText("Cadastrar Novo Imóvel");
        BtnCadastrar.setBorderPainted(false);
        BtnCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadastrarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Cadastro Contrato Financeiro");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Aqui é possível cadastrar os contratos, e registrá-los.");

        ValorTotalLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ValorTotalLabel.setText("Valor Total:");

        IdImovelLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        IdImovelLabel.setText("IdImóvel:");

        SituacaoComboLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SituacaoComboLabel.setText("Situação:");

        BtnCancelar.setBackground(new java.awt.Color(30, 122, 206));
        BtnCancelar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        BtnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        BtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Close.png"))); // NOI18N
        BtnCancelar.setText("Cancelar");
        BtnCancelar.setBorderPainted(false);
        BtnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        BtnRetornar.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        BtnRetornar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/U Turn to Left_1.png"))); // NOI18N
        BtnRetornar.setText("Retornar");
        BtnRetornar.setAlignmentY(0.0F);
        BtnRetornar.setBorderPainted(false);
        BtnRetornar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnRetornar.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        BtnRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRetornarActionPerformed(evt);
            }
        });

        ValorTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        ValorTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValorTotalActionPerformed(evt);
            }
        });
        ValorTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ValorTotalKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ValorTotalKeyTyped(evt);
            }
        });

        ValorParcela.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        ValorParcela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValorParcelaActionPerformed(evt);
            }
        });
        ValorParcela.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ValorParcelaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ValorParcelaKeyTyped(evt);
            }
        });

        ValorParcelaLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ValorParcelaLabel.setText("Valor Parcela:");

        NParcelas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        NParcelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NParcelasActionPerformed(evt);
            }
        });
        NParcelas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NParcelasKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NParcelasKeyTyped(evt);
            }
        });

        NParcelasLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NParcelasLabel.setText("N° Parcelas:");

        NomeLocador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        NomeLocador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeLocadorActionPerformed(evt);
            }
        });
        NomeLocador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NomeLocadorKeyPressed(evt);
            }
        });

        NomeLocadorLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NomeLocadorLabel.setText("Nome Locador:");

        NomeLocatario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        NomeLocatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeLocatarioActionPerformed(evt);
            }
        });
        NomeLocatario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NomeLocatarioKeyPressed(evt);
            }
        });

        NomeLocatarioLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NomeLocatarioLabel.setText("Nome Locatário:");

        NomeContratoLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NomeContratoLabel1.setText("Nome Contrato");

        NomeContrato.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        NomeContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeContratoActionPerformed(evt);
            }
        });
        NomeContrato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NomeContratoKeyPressed(evt);
            }
        });

        idimoveisFinanceiro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "item 1" }));
        idimoveisFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idimoveisFinanceiroActionPerformed(evt);
            }
        });

        IdImovelLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        IdImovelLabel1.setText("Nome imovel");

        nomeImovelFinanceiro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        nomeImovelFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeImovelFinanceiroActionPerformed(evt);
            }
        });
        nomeImovelFinanceiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nomeImovelFinanceiroKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nomeImovelFinanceiroKeyTyped(evt);
            }
        });

        situacaoComboFinanceiro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Atrasado", "Inativo" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(BtnRetornar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(NomeContratoLabel1)
                        .addGap(310, 310, 310)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SituacaoComboLabel)
                            .addComponent(IdImovelLabel1)
                            .addComponent(nomeImovelFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 286, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(BtnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(situacaoComboFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(NomeLocatario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                                                .addComponent(NomeLocador, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(ValorParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(NomeContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(ValorParcelaLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(NParcelasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(ValorTotalLabel)
                                                        .addComponent(NParcelas, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                                        .addComponent(ValorTotal)))))
                                        .addComponent(NomeLocadorLabel)
                                        .addComponent(NomeLocatarioLabel))
                                    .addGap(66, 66, 66)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(IdImovelLabel)
                                        .addComponent(idimoveisFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(BtnRetornar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(76, 76, 76)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NParcelasLabel)
                    .addComponent(ValorParcelaLabel)
                    .addComponent(IdImovelLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ValorParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idimoveisFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeContratoLabel1)
                    .addComponent(ValorTotalLabel)
                    .addComponent(IdImovelLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeImovelFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeLocadorLabel)
                    .addComponent(SituacaoComboLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeLocador, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(situacaoComboFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(NomeLocatarioLabel)
                .addGap(14, 14, 14)
                .addComponent(NomeLocatario, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout PainelCentralLayout = new javax.swing.GroupLayout(PainelCentral);
        PainelCentral.setLayout(PainelCentralLayout);
        PainelCentralLayout.setHorizontalGroup(
            PainelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCentralLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(PainelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PainelCentralLayout.setVerticalGroup(
            PainelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCentralLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 888, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PainelCentral, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 773, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PainelCentral, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRetornarActionPerformed
        // TODO add your handling code here:
        Financeiro FinanceiroPrincipal = new Financeiro();
        ShowPanel(FinanceiroPrincipal);
    }//GEN-LAST:event_BtnRetornarActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        // TODO add your handling code here:
        String[] options = {"Sim", "Cancelar"};
        int resposta = JOptionPane.showOptionDialog(
                this,
                "Esta ação apagará todos os campos, tem certeza?",
                "Confirmação",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.WARNING_MESSAGE,
                null,
                options,
                options[0]
        );
        if (resposta == 0) {

        } else {
            BtnCancelar.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void BtnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadastrarActionPerformed
        // TODO add your handling code here:
        try {

            int idImovelFinanceiro = Integer.parseInt(idimoveisFinanceiro.getSelectedItem().toString());
            String nomeContrato = NomeContrato.getText();
            String situacaoTexto = situacaoComboFinanceiro.getSelectedItem().toString();
            String valorParcela = ValorParcela.getText();
            String numeroParcelas = NParcelas.getText();
            String valorTotal = ValorTotal.getText();
            String locatario = NomeLocatario.getText();
            String locador = NomeLocador.getText();

            FinanceiroModel financeiro = new FinanceiroModel(idImovelFinanceiro, nomeContrato, situacaoTexto, valorParcela, numeroParcelas,
                    valorTotal, locatario, locador);

            JBDCCadastroFinanceiro dao = new JBDCCadastroFinanceiro();
            dao.inserirContratoFinanceiro(financeiro);

            JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar: " + ex.getMessage());
        }

        String CheckNome = NomeContrato.getText();
        if (ValorParcela.getText().isEmpty()
                && NParcelas.getText().isEmpty() && ValorTotal.getText().isEmpty() && NomeLocador.getText().isEmpty()
                && NomeLocatario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "O nome do imóvel não pode estar vazio!");
        } else {
            String[] options = {"Sim", "Não"};
            int resposta = JOptionPane.showOptionDialog(
                    this,
                    "Cadastro Registrado!" + "\n"
                    + "Nome do Contrato: " + NomeContrato.getText() + "\n"
                    + "IdImóvel: " + idimoveisFinanceiro.getSelectedItem() + "\n"
                    + "Locador: " + NomeLocador.getText() + "\n"
                    + "Locatário: " + NomeLocatario.getText() + "\n"
                    + "Valor Parcela: " + ValorParcela.getText() + "\n"
                    + "Número Parcelas: " + NParcelas.getText() + "\n"
                    + "Valor Total: " + ValorTotal.getText() + "\n"
                    + "Situação: " + situacaoComboFinanceiro.getSelectedItem() + "\n\n\n"
                    + "Cadastrar novo Contrato?" + "\n",
                    "Confirmação de Cadastro",
                    JOptionPane.DEFAULT_OPTION,
                    JOptionPane.WARNING_MESSAGE,
                    null,
                    options,
                    options[0]);
            if (resposta == 1) {
            } else {
                idimoveisFinanceiro.setSelectedIndex(-1);
                NomeLocador.setText("");
                NomeLocatario.setText("");
                ValorParcela.setText("");
                NParcelas.setText("");
                ValorTotal.setText("");
                situacaoComboFinanceiro.setSelectedIndex(-1);
            }
        }
    }//GEN-LAST:event_BtnCadastrarActionPerformed

    private void ValorTotalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ValorTotalKeyPressed
        // TODO add your handling code here:
        if (evt.getExtendedKeyCode() == evt.VK_ENTER) {
            NomeLocador.requestFocus();
        }
    }//GEN-LAST:event_ValorTotalKeyPressed

    private void ValorTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ValorTotalKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_ValorTotalKeyTyped

    private void ValorTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValorTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValorTotalActionPerformed

    private void ValorParcelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValorParcelaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValorParcelaActionPerformed

    private void ValorParcelaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ValorParcelaKeyPressed
        // TODO add your handling code here:
        if (evt.getExtendedKeyCode() == evt.VK_ENTER) {
            NParcelas.requestFocus();
        }
    }//GEN-LAST:event_ValorParcelaKeyPressed

    private void ValorParcelaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ValorParcelaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_ValorParcelaKeyTyped

    private void NParcelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NParcelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NParcelasActionPerformed

    private void NParcelasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NParcelasKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_NParcelasKeyPressed

    private void NParcelasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NParcelasKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_NParcelasKeyTyped

    private void NomeLocadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeLocadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeLocadorActionPerformed

    private void NomeLocadorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NomeLocadorKeyPressed
        // TODO add your handling code here:
        if (evt.getExtendedKeyCode() == evt.VK_ENTER) {
            NomeLocatario.requestFocus();
        }
    }//GEN-LAST:event_NomeLocadorKeyPressed

    private void NomeLocatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeLocatarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeLocatarioActionPerformed

    private void NomeLocatarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NomeLocatarioKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeLocatarioKeyPressed

    private void NomeContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeContratoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeContratoActionPerformed

    private void NomeContratoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NomeContratoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeContratoKeyPressed

    private void idimoveisFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idimoveisFinanceiroActionPerformed

        JBDCCadastroImovel imovelDAO = new JBDCCadastroImovel();
        ArrayList<Integer> idsImoveis = imovelDAO.buscarIdsImoveis();

        for (Integer id : idsImoveis) {
            idimoveisFinanceiro.addItem(id.toString());
        }


    }//GEN-LAST:event_idimoveisFinanceiroActionPerformed

    private void nomeImovelFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeImovelFinanceiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeImovelFinanceiroActionPerformed

    private void nomeImovelFinanceiroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeImovelFinanceiroKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeImovelFinanceiroKeyPressed

    private void nomeImovelFinanceiroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeImovelFinanceiroKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeImovelFinanceiroKeyTyped

    private void ShowPanel(JPanel p) {
        p.setSize(799, 700);
        p.setLocation(0, 0);

        PainelCentral.removeAll();
        PainelCentral.add(p, BorderLayout.CENTER);
        PainelCentral.revalidate();
        PainelCentral.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCadastrar;
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnRetornar;
    private javax.swing.JLabel IdImovelLabel;
    private javax.swing.JLabel IdImovelLabel1;
    private javax.swing.JTextField NParcelas;
    private javax.swing.JLabel NParcelasLabel;
    private javax.swing.JTextField NomeContrato;
    private javax.swing.JLabel NomeContratoLabel1;
    private javax.swing.JTextField NomeLocador;
    private javax.swing.JLabel NomeLocadorLabel;
    private javax.swing.JTextField NomeLocatario;
    private javax.swing.JLabel NomeLocatarioLabel;
    private javax.swing.JPanel PainelCentral;
    private javax.swing.JLabel SituacaoComboLabel;
    private javax.swing.JTextField ValorParcela;
    private javax.swing.JLabel ValorParcelaLabel;
    private javax.swing.JTextField ValorTotal;
    private javax.swing.JLabel ValorTotalLabel;
    private javax.swing.JComboBox<String> idimoveisFinanceiro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField nomeImovelFinanceiro;
    private javax.swing.JComboBox<String> situacaoComboFinanceiro;
    // End of variables declaration//GEN-END:variables
}
