/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Financeiro;

import Imóvel.*;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.plaf.basic.BasicButtonUI;
import Imóvel.Imovel;
import javax.swing.JOptionPane;

/**
 *
 * @author pedro
 */
public class CadastroFinanceiro extends javax.swing.JPanel {

    /**
     * Creates new form CadastroImovel
     */
    public CadastroFinanceiro() {
        initComponents();
        JButton [] btns = {BtnCadastrar, BtnCancelar,BtnRetornar};
       for(JButton btn : btns){
           btn.setBackground(new Color(30,122,206));
           btn.setUI(new BasicButtonUI());
           BtnRetornar.setBackground(Color.WHITE);
           btn.addMouseListener(new MouseListener(){
               @Override
               public void mouseClicked(MouseEvent e){
                   
               }
               @Override
               public void mousePressed(MouseEvent e){
                   
               }
               @Override 
                public void mouseReleased(MouseEvent e){
                   
               }
               @Override
               public void mouseEntered(MouseEvent e){
                    btn.setBackground(new Color(47,141,227));
                    BtnRetornar.setBackground(Color.WHITE);
               }
               @Override
               public void mouseExited(MouseEvent e){
                   btn.setBackground(new Color(30,122,206));
                   BtnRetornar.setBackground(Color.WHITE);
               }
           
           });
           }
   
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelCentral = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        BtnCadastrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NomeContratoLabel = new javax.swing.JLabel();
        NomeContrato = new javax.swing.JTextField();
        ValorTotalLabel = new javax.swing.JLabel();
        IdImovel = new javax.swing.JTextField();
        IdImovelLabel = new javax.swing.JLabel();
        SituacaoComboLabel = new javax.swing.JLabel();
        SituacaoCombo = new javax.swing.JComboBox<>();
        BtnCancelar = new javax.swing.JButton();
        BtnRetornar = new javax.swing.JButton();
        ValorTotal = new javax.swing.JTextField();
        ValorParcela = new javax.swing.JTextField();
        ValorParcelaLabel = new javax.swing.JLabel();
        NParcelas = new javax.swing.JTextField();
        NParcelasLabel = new javax.swing.JLabel();
        ComissaoImobil = new javax.swing.JTextField();
        ComissaoImobilLabel = new javax.swing.JLabel();
        IPTULabel = new javax.swing.JLabel();
        Energia = new javax.swing.JTextField();
        EnergiaLabel = new javax.swing.JLabel();
        Agua = new javax.swing.JTextField();
        AguaLabel = new javax.swing.JLabel();
        Luz = new javax.swing.JTextField();
        LuzLabel = new javax.swing.JLabel();
        Lixo = new javax.swing.JTextField();
        LixoLabel = new javax.swing.JLabel();
        Gas = new javax.swing.JTextField();
        GasLabel = new javax.swing.JLabel();
        IPTU = new javax.swing.JTextField();
        Outros = new javax.swing.JTextField();
        OutrosLabel = new javax.swing.JLabel();
        Condominio = new javax.swing.JTextField();
        CondominioLabel = new javax.swing.JLabel();
        ValorAbono = new javax.swing.JTextField();
        ValorAbonoLabel = new javax.swing.JLabel();
        NomeLocador = new javax.swing.JTextField();
        NomeLocadorLabel = new javax.swing.JLabel();
        NomeLocatario = new javax.swing.JTextField();
        NomeLocatarioLabel = new javax.swing.JLabel();

        PainelCentral.setBackground(new java.awt.Color(36, 114, 221));
        PainelCentral.setForeground(new java.awt.Color(255, 255, 255));
        PainelCentral.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("/Home/Financeiro/Cadastrar");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Imobils, Sistema Imobiliário");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        BtnCadastrar.setBackground(new java.awt.Color(30, 122, 206));
        BtnCadastrar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        BtnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        BtnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Edit_1.png"))); // NOI18N
        BtnCadastrar.setText("Cadastrar Novo Imóvel");
        BtnCadastrar.setBorderPainted(false);
        BtnCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadastrarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Cadastro Contrato Financeiro");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Aqui é possível cadastrar os contratos, e registrá-los.");

        NomeContratoLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NomeContratoLabel.setText("Nome Contrato:");

        NomeContrato.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        NomeContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeContratoActionPerformed(evt);
            }
        });
        NomeContrato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NomeContratoKeyPressed(evt);
            }
        });

        ValorTotalLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ValorTotalLabel.setText("Valor Total:");

        IdImovel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        IdImovel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                IdImovelKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IdImovelKeyTyped(evt);
            }
        });

        IdImovelLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        IdImovelLabel.setText("IdImóvel:");

        SituacaoComboLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SituacaoComboLabel.setText("Situação:");

        SituacaoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular", "Atrasado", "Pendente" }));

        BtnCancelar.setBackground(new java.awt.Color(30, 122, 206));
        BtnCancelar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        BtnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        BtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Close.png"))); // NOI18N
        BtnCancelar.setText("Cancelar");
        BtnCancelar.setBorderPainted(false);
        BtnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        BtnRetornar.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        BtnRetornar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/U Turn to Left_1.png"))); // NOI18N
        BtnRetornar.setText("Retornar");
        BtnRetornar.setAlignmentY(0.0F);
        BtnRetornar.setBorderPainted(false);
        BtnRetornar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnRetornar.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        BtnRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRetornarActionPerformed(evt);
            }
        });

        ValorTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        ValorTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValorTotalActionPerformed(evt);
            }
        });
        ValorTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ValorTotalKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ValorTotalKeyTyped(evt);
            }
        });

        ValorParcela.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        ValorParcela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValorParcelaActionPerformed(evt);
            }
        });
        ValorParcela.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ValorParcelaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ValorParcelaKeyTyped(evt);
            }
        });

        ValorParcelaLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ValorParcelaLabel.setText("Valor Parcela:");

        NParcelas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        NParcelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NParcelasActionPerformed(evt);
            }
        });
        NParcelas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NParcelasKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NParcelasKeyTyped(evt);
            }
        });

        NParcelasLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NParcelasLabel.setText("N° Parcelas:");

        ComissaoImobil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        ComissaoImobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComissaoImobilActionPerformed(evt);
            }
        });
        ComissaoImobil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ComissaoImobilKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ComissaoImobilKeyTyped(evt);
            }
        });

        ComissaoImobilLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ComissaoImobilLabel.setText("Comissão Imobiliária:");

        IPTULabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        IPTULabel.setText("IPTU:");

        Energia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Energia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnergiaActionPerformed(evt);
            }
        });
        Energia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EnergiaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EnergiaKeyTyped(evt);
            }
        });

        EnergiaLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EnergiaLabel.setText("Energia:");

        Agua.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Agua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AguaActionPerformed(evt);
            }
        });
        Agua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AguaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AguaKeyTyped(evt);
            }
        });

        AguaLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AguaLabel.setText("Água:");

        Luz.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Luz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LuzActionPerformed(evt);
            }
        });
        Luz.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LuzKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                LuzKeyTyped(evt);
            }
        });

        LuzLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LuzLabel.setText("Luz:");

        Lixo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Lixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LixoActionPerformed(evt);
            }
        });
        Lixo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LixoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                LixoKeyTyped(evt);
            }
        });

        LixoLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LixoLabel.setText("Lixo:");

        Gas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Gas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GasActionPerformed(evt);
            }
        });
        Gas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                GasKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                GasKeyTyped(evt);
            }
        });

        GasLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        GasLabel.setText("Gás:");

        IPTU.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        IPTU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IPTUActionPerformed(evt);
            }
        });
        IPTU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                IPTUKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IPTUKeyTyped(evt);
            }
        });

        Outros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Outros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OutrosActionPerformed(evt);
            }
        });
        Outros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                OutrosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                OutrosKeyTyped(evt);
            }
        });

        OutrosLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        OutrosLabel.setText("Outros:");

        Condominio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Condominio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CondominioActionPerformed(evt);
            }
        });
        Condominio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CondominioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CondominioKeyTyped(evt);
            }
        });

        CondominioLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CondominioLabel.setText("Condomínio:");

        ValorAbono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        ValorAbono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValorAbonoActionPerformed(evt);
            }
        });
        ValorAbono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ValorAbonoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ValorAbonoKeyTyped(evt);
            }
        });

        ValorAbonoLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ValorAbonoLabel.setText("Valor Abono:");

        NomeLocador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        NomeLocador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeLocadorActionPerformed(evt);
            }
        });
        NomeLocador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NomeLocadorKeyPressed(evt);
            }
        });

        NomeLocadorLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NomeLocadorLabel.setText("Nome Locador:");

        NomeLocatario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        NomeLocatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeLocatarioActionPerformed(evt);
            }
        });
        NomeLocatario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NomeLocatarioKeyPressed(evt);
            }
        });

        NomeLocatarioLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NomeLocatarioLabel.setText("Nome Locatário:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(BtnRetornar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NomeLocadorLabel)
                            .addComponent(NomeLocador, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(NomeLocatarioLabel)
                                .addGap(273, 276, Short.MAX_VALUE))
                            .addComponent(NomeLocatario)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(BtnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                                    .addComponent(NomeContratoLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NomeContrato, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(IdImovelLabel)
                                    .addComponent(IdImovel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SituacaoComboLabel)
                                    .addComponent(SituacaoCombo, 0, 210, Short.MAX_VALUE)
                                    .addComponent(ComissaoImobilLabel)
                                    .addComponent(ComissaoImobil)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(IPTULabel)
                                    .addComponent(IPTU, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EnergiaLabel)
                                    .addComponent(Energia, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AguaLabel)
                                    .addComponent(Agua, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LuzLabel)
                                    .addComponent(Luz, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LixoLabel)
                                    .addComponent(Lixo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(GasLabel)
                                    .addComponent(Gas)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ValorAbonoLabel)
                                    .addComponent(ValorAbono, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ValorParcelaLabel)
                                    .addComponent(ValorParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NParcelasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(222, 222, 222)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OutrosLabel)
                            .addComponent(Outros, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CondominioLabel)
                            .addComponent(Condominio, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(ValorTotalLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(ValorTotal))))
                .addGap(42, 42, 42))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(BtnRetornar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(NomeContratoLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(NomeContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(SituacaoComboLabel)
                                        .addGap(32, 32, 32))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(IdImovelLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(IdImovel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(SituacaoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(ValorParcelaLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(ValorParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(NParcelasLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(NParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(ComissaoImobilLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(ComissaoImobil, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(ValorAbonoLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ValorAbono, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(EnergiaLabel)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGap(26, 26, 26)
                                            .addComponent(Energia, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(IPTULabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(IPTU, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(AguaLabel)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGap(26, 26, 26)
                                            .addComponent(Agua, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(LuzLabel)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGap(26, 26, 26)
                                            .addComponent(Luz, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(LixoLabel)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGap(26, 26, 26)
                                            .addComponent(Lixo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(GasLabel)
                                        .addGap(32, 32, 32))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Gas, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(OutrosLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Outros, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(CondominioLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Condominio, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(ValorTotalLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NomeLocadorLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NomeLocador, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NomeLocatarioLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NomeLocatario, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout PainelCentralLayout = new javax.swing.GroupLayout(PainelCentral);
        PainelCentral.setLayout(PainelCentralLayout);
        PainelCentralLayout.setHorizontalGroup(
            PainelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCentralLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(PainelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PainelCentralLayout.setVerticalGroup(
            PainelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCentralLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 802, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PainelCentral, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 724, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PainelCentral, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRetornarActionPerformed
        // TODO add your handling code here:
        Imovel Imovel = new Imovel();
        ShowPanel(Imovel);
    }//GEN-LAST:event_BtnRetornarActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        // TODO add your handling code here:
        String[] options = {"Sim", "Cancelar"};
        int resposta = JOptionPane.showOptionDialog(
            this,
            "Esta ação apagará todos os campos, tem certeza?",
            "Confirmação",
            JOptionPane.DEFAULT_OPTION,
            JOptionPane.WARNING_MESSAGE,
            null,
            options,
            options[0]
        );
        if (resposta == 0) {

        } else {
            BtnCancelar.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void IdImovelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IdImovelKeyTyped
        // TODO add your handling code here:
        char keyPress = evt.getKeyChar();
        if(!Character.isDigit(keyPress)){
            evt.consume();
        }
    }//GEN-LAST:event_IdImovelKeyTyped

    private void IdImovelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IdImovelKeyPressed
        // TODO add your handling code here:
        if(evt.getExtendedKeyCode() == evt.VK_ENTER){
            ValorAbono.requestFocus();
        }
    }//GEN-LAST:event_IdImovelKeyPressed

    private void NomeContratoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NomeContratoKeyPressed
        // TODO add your handling code here:
        if(evt.getExtendedKeyCode() == evt.VK_ENTER){
            IdImovel.requestFocus();
        }
    }//GEN-LAST:event_NomeContratoKeyPressed

    private void NomeContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeContratoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_NomeContratoActionPerformed

    private void BtnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadastrarActionPerformed
        // TODO add your handling code here:
        String CheckNome = NomeContrato.getText();
        if(NomeContrato.getText().isEmpty() && IdImovel.getText().isEmpty() && ValorAbono.getText().isEmpty() && ValorParcela.getText().isEmpty()
            && NParcelas.getText().isEmpty() && ComissaoImobil.getText().isEmpty()
            && IPTU.getText().isEmpty() && Energia.getText().isEmpty() && Agua.getText().isEmpty() && Luz.getText().isEmpty() && Lixo.getText().isEmpty() 
            && Gas.getText().isEmpty() && Outros.getText().isEmpty() && Condominio.getText().isEmpty() && ValorTotal.getText().isEmpty() && NomeLocador.getText().isEmpty()
            && NomeLocatario.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "O nome do imóvel não pode estar vazio!");
        }else{
            String[] options = {"Sim", "Não"};
            int resposta = JOptionPane.showOptionDialog(
                this,
                "Cadastro Registrado!"+ "\n" +
                "Nome do Contrato: " + NomeContrato.getText() + "\n" +
                "IdImóvel: " + IdImovel.getText() + "\n" +
                "Locador: " + NomeLocador.getText() + "\n" +
                "Locatário: " + NomeLocatario.getText() + "\n" +
                "IPTU: " + IPTU.getText() + "\n" +
                "Energia: " + Energia.getText() + "\n" +
                "Água: " + Agua.getText() + "\n" +
                "Luz: " + Luz.getText() + "\n" +
                "Lixo: " + Lixo.getText() + "\n" +
                "Gás: " + Gas.getText() + "\n" +
                "Condomínio: " + Condominio.getText() + "\n" +
                "Outros: " + Outros.getText() + "\n\n\n" +
                "Valor Parcela: " + ValorParcela.getText() + "\n" +
                "Número Parcelas: " + NParcelas.getText() + "\n" +
                "Valor Abono: " + ValorAbono.getText() + "\n" +
                "Comissão Imobiliária: " + ComissaoImobil.getText() + "\n" +
                "Valor Total: " + ValorTotal.getText() + "\n" +
                "Situação: " + SituacaoCombo.getSelectedItem() + "\n\n\n" +
                "Cadastrar novo Contrato?" +"\n",
                "Confirmação de Cadastro",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.WARNING_MESSAGE,
                null,
                options,
                options[0]);
            if (resposta == 1) {
            }else{
                NomeContrato.setText("");
                IdImovel.setText("");
                NomeLocador.setText("");
                NomeLocatario.setText("");
                IPTU.setText("");
                Energia.setText("");
                Agua.setText("");
                Luz.setText("");
                Lixo.setText("");
                Gas.setText("");
                Condominio.setText("");
                ValorParcela.setText("");
                NParcelas.setText("");
                ValorAbono.setText("");
                ComissaoImobil.setText("");
                ValorTotal.setText("");
                Outros.setText("");
                
                
                SituacaoCombo.setSelectedIndex(-1);
                NomeContrato.requestFocus();
            }
        }
    }//GEN-LAST:event_BtnCadastrarActionPerformed

    private void ValorTotalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ValorTotalKeyPressed
        // TODO add your handling code here:
         if(evt.getExtendedKeyCode() == evt.VK_ENTER){
            NomeLocador.requestFocus();
        }
    }//GEN-LAST:event_ValorTotalKeyPressed

    private void ValorTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ValorTotalKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_ValorTotalKeyTyped

    private void ValorTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValorTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValorTotalActionPerformed

    private void ValorParcelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValorParcelaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValorParcelaActionPerformed

    private void ValorParcelaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ValorParcelaKeyPressed
        // TODO add your handling code here:
         if(evt.getExtendedKeyCode() == evt.VK_ENTER){
            NParcelas.requestFocus();
        }
    }//GEN-LAST:event_ValorParcelaKeyPressed

    private void ValorParcelaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ValorParcelaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_ValorParcelaKeyTyped

    private void NParcelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NParcelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NParcelasActionPerformed

    private void NParcelasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NParcelasKeyPressed
        // TODO add your handling code here:
        if(evt.getExtendedKeyCode() == evt.VK_ENTER){
            ComissaoImobil.requestFocus();
        }
    }//GEN-LAST:event_NParcelasKeyPressed

    private void NParcelasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NParcelasKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_NParcelasKeyTyped

    private void ComissaoImobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComissaoImobilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComissaoImobilActionPerformed

    private void ComissaoImobilKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ComissaoImobilKeyPressed
        // TODO add your handling code here:
        if(evt.getExtendedKeyCode() == evt.VK_ENTER){
            IPTU.requestFocus();
        }
    }//GEN-LAST:event_ComissaoImobilKeyPressed

    private void ComissaoImobilKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ComissaoImobilKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_ComissaoImobilKeyTyped

    private void EnergiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnergiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnergiaActionPerformed

    private void EnergiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EnergiaKeyPressed
        // TODO add your handling code here:
         if(evt.getExtendedKeyCode() == evt.VK_ENTER){
            Agua.requestFocus();
        }
    }//GEN-LAST:event_EnergiaKeyPressed

    private void EnergiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EnergiaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_EnergiaKeyTyped

    private void AguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AguaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AguaActionPerformed

    private void AguaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AguaKeyPressed
        // TODO add your handling code here:
         if(evt.getExtendedKeyCode() == evt.VK_ENTER){
            Luz.requestFocus();
        }
    }//GEN-LAST:event_AguaKeyPressed

    private void AguaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AguaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_AguaKeyTyped

    private void LuzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LuzActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LuzActionPerformed

    private void LuzKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LuzKeyPressed
        // TODO add your handling code here:
         if(evt.getExtendedKeyCode() == evt.VK_ENTER){
            Lixo.requestFocus();
        }
    }//GEN-LAST:event_LuzKeyPressed

    private void LuzKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LuzKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_LuzKeyTyped

    private void LixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LixoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LixoActionPerformed

    private void LixoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LixoKeyPressed
        // TODO add your handling code here:
         if(evt.getExtendedKeyCode() == evt.VK_ENTER){
            Gas.requestFocus();
        }
    }//GEN-LAST:event_LixoKeyPressed

    private void LixoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LixoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_LixoKeyTyped

    private void GasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GasActionPerformed

    private void GasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GasKeyPressed
        // TODO add your handling code here:
         if(evt.getExtendedKeyCode() == evt.VK_ENTER){
            Outros.requestFocus();
        }
    }//GEN-LAST:event_GasKeyPressed

    private void GasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GasKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_GasKeyTyped

    private void IPTUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IPTUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IPTUActionPerformed

    private void IPTUKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IPTUKeyPressed
        // TODO add your handling code here:
        if(evt.getExtendedKeyCode() == evt.VK_ENTER){
            Energia.requestFocus();
        }
    }//GEN-LAST:event_IPTUKeyPressed

    private void IPTUKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IPTUKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_IPTUKeyTyped

    private void OutrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OutrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OutrosActionPerformed

    private void OutrosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_OutrosKeyPressed
        // TODO add your handling code here:
         if(evt.getExtendedKeyCode() == evt.VK_ENTER){
            Condominio.requestFocus();
        }
    }//GEN-LAST:event_OutrosKeyPressed

    private void OutrosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_OutrosKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_OutrosKeyTyped

    private void CondominioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CondominioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CondominioActionPerformed

    private void CondominioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CondominioKeyPressed
        // TODO add your handling code here:
         if(evt.getExtendedKeyCode() == evt.VK_ENTER){
            ValorTotal.requestFocus();
        }
    }//GEN-LAST:event_CondominioKeyPressed

    private void CondominioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CondominioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_CondominioKeyTyped

    private void ValorAbonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValorAbonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValorAbonoActionPerformed

    private void ValorAbonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ValorAbonoKeyPressed
        // TODO add your handling code here:
        if(evt.getExtendedKeyCode() == evt.VK_ENTER){
            ValorParcela.requestFocus();
        }
    }//GEN-LAST:event_ValorAbonoKeyPressed

    private void ValorAbonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ValorAbonoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_ValorAbonoKeyTyped

    private void NomeLocadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeLocadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeLocadorActionPerformed

    private void NomeLocadorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NomeLocadorKeyPressed
        // TODO add your handling code here:
         if(evt.getExtendedKeyCode() == evt.VK_ENTER){
            NomeLocatario.requestFocus();
        }
    }//GEN-LAST:event_NomeLocadorKeyPressed

    private void NomeLocatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeLocatarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeLocatarioActionPerformed

    private void NomeLocatarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NomeLocatarioKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeLocatarioKeyPressed

    
    private void ShowPanel(JPanel p){
    p.setSize(799, 700);
    p.setLocation(0, 0);
    
    PainelCentral.removeAll();
    PainelCentral.add(p, BorderLayout.CENTER); 
    PainelCentral.revalidate();
    PainelCentral.repaint();    
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Agua;
    private javax.swing.JLabel AguaLabel;
    private javax.swing.JButton BtnCadastrar;
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnRetornar;
    private javax.swing.JTextField ComissaoImobil;
    private javax.swing.JLabel ComissaoImobilLabel;
    private javax.swing.JTextField Condominio;
    private javax.swing.JLabel CondominioLabel;
    private javax.swing.JTextField Energia;
    private javax.swing.JLabel EnergiaLabel;
    private javax.swing.JTextField Gas;
    private javax.swing.JLabel GasLabel;
    private javax.swing.JTextField IPTU;
    private javax.swing.JLabel IPTULabel;
    private javax.swing.JTextField IdImovel;
    private javax.swing.JLabel IdImovelLabel;
    private javax.swing.JTextField Lixo;
    private javax.swing.JLabel LixoLabel;
    private javax.swing.JTextField Luz;
    private javax.swing.JLabel LuzLabel;
    private javax.swing.JTextField NParcelas;
    private javax.swing.JLabel NParcelasLabel;
    private javax.swing.JTextField NomeContrato;
    private javax.swing.JLabel NomeContratoLabel;
    private javax.swing.JTextField NomeLocador;
    private javax.swing.JLabel NomeLocadorLabel;
    private javax.swing.JTextField NomeLocatario;
    private javax.swing.JLabel NomeLocatarioLabel;
    private javax.swing.JTextField Outros;
    private javax.swing.JLabel OutrosLabel;
    private javax.swing.JPanel PainelCentral;
    private javax.swing.JComboBox<String> SituacaoCombo;
    private javax.swing.JLabel SituacaoComboLabel;
    private javax.swing.JTextField ValorAbono;
    private javax.swing.JLabel ValorAbonoLabel;
    private javax.swing.JTextField ValorParcela;
    private javax.swing.JLabel ValorParcelaLabel;
    private javax.swing.JTextField ValorTotal;
    private javax.swing.JLabel ValorTotalLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
