/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Financeiro;

import DAO.JBDCCadastroFinanceiro;
import DAO.JBDCCadastroImovel;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.plaf.basic.BasicButtonUI;
import Imóvel.Imovel;
import javax.swing.JOptionPane;
import Financeiro.Financeiro;
import Model.FinanceiroModel;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Patryk
 */
public class CadastroFinanceiro extends javax.swing.JPanel {

    /**
     * Creates new form CadastroImovel
     */
    public CadastroFinanceiro() {
        initComponents();
        MostrarListaImoveis();
        MostrarListaClientes();
        JButton[] btns = {BtnCadastrar, BtnCancelar, BtnRetornar};
        for (JButton btn : btns) {
            btn.setBackground(new Color(30, 122, 206));
            btn.setUI(new BasicButtonUI());
            BtnRetornar.setBackground(Color.WHITE);
            btn.addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent e) {

                }

                @Override
                public void mousePressed(MouseEvent e) {

                }

                @Override
                public void mouseReleased(MouseEvent e) {

                }

                @Override
                public void mouseEntered(MouseEvent e) {
                    btn.setBackground(new Color(47, 141, 227));
                    BtnRetornar.setBackground(Color.WHITE);
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    btn.setBackground(new Color(30, 122, 206));
                    BtnRetornar.setBackground(Color.WHITE);
                }

            });
        }

    }

    public void MostrarListaImoveis() {

        nomeImovelFinanceiro.setText("");
        DefaultTableModel model = (DefaultTableModel) tableImoveis.getModel();

        if (model.getColumnCount() == 0) {
            model.addColumn("ID Imovel");
            model.addColumn("Imovel");
        }

        model.setRowCount(0);

        JBDCCadastroFinanceiro ListaProdutos = new JBDCCadastroFinanceiro();
        ArrayList<FinanceiroModel> listaProdutos = ListaProdutos.MostrarImoveisTabela();

        for (FinanceiroModel produto : listaProdutos) {
            Object[] row = {
                produto.getIdimovel(),
                produto.getNome_imovel(),};
            model.addRow(row);
        }
    }

    public void MostrarListaClientes() {

        nomeClienteFinanceiro.setText("");
        DefaultTableModel model = (DefaultTableModel) tableClientes.getModel();

        if (model.getColumnCount() == 0) {
            model.addColumn("ID Locador");
            model.addColumn("Locador");
        }

        model.setRowCount(0);

        JBDCCadastroFinanceiro ListaProdutos = new JBDCCadastroFinanceiro();
        ArrayList<FinanceiroModel> listaProdutos = ListaProdutos.MostrarClientesTabela();

        for (FinanceiroModel produto : listaProdutos) {
            Object[] row = {
                produto.getIdimovel(),
                produto.getNome_imovel(),};
            model.addRow(row);
        }
    }

    private void entregaDadosPesquisado(ArrayList<FinanceiroModel> imoveis) {

        DefaultTableModel modelo = (DefaultTableModel) tableImoveis.getModel();
        modelo.setRowCount(0);

        for (FinanceiroModel imovel : imoveis) {
            modelo.addRow(new Object[]{
                imovel.getIdimovel(),
                imovel.getNome_imovel()
            });
        }
    }

    private void entregaClientePesquisado(ArrayList<FinanceiroModel> imoveis) {

        DefaultTableModel modelo = (DefaultTableModel) tableClientes.getModel();
        modelo.setRowCount(0);

        for (FinanceiroModel imovel : imoveis) {
            modelo.addRow(new Object[]{
                imovel.getIdimovel(),
                imovel.getNome_imovel()
            });
        }
    }
    
    private void limparCamposCadastro() {
    NomeContrato.setText("");
    ValorParcela.setText("");
    NParcelas.setText("");
    ValorTotal.setText("");
    situacaoComboFinanceiro.setSelectedIndex(-1);
    tableClientes.clearSelection();
    tableImoveis.clearSelection();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelCentral = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        BtnCadastrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ValorTotalLabel = new javax.swing.JLabel();
        SituacaoComboLabel = new javax.swing.JLabel();
        BtnCancelar = new javax.swing.JButton();
        BtnRetornar = new javax.swing.JButton();
        ValorTotal = new javax.swing.JTextField();
        ValorParcela = new javax.swing.JTextField();
        ValorParcelaLabel = new javax.swing.JLabel();
        NParcelas = new javax.swing.JTextField();
        NParcelasLabel = new javax.swing.JLabel();
        nomeClienteFinanceiro = new javax.swing.JTextField();
        NomeLocadorLabel = new javax.swing.JLabel();
        NomeContratoLabel1 = new javax.swing.JLabel();
        NomeContrato = new javax.swing.JTextField();
        IdImovelLabel1 = new javax.swing.JLabel();
        nomeImovelFinanceiro = new javax.swing.JTextField();
        situacaoComboFinanceiro = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableImoveis = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableClientes = new javax.swing.JTable();
        BtnCadastrar1 = new javax.swing.JButton();
        BtnProcurarCliente = new javax.swing.JButton();

        PainelCentral.setBackground(new java.awt.Color(36, 114, 221));
        PainelCentral.setForeground(new java.awt.Color(255, 255, 255));
        PainelCentral.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("/Home/Financeiro/Cadastrar");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Imobils, Sistema Imobiliário");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        BtnCadastrar.setBackground(new java.awt.Color(30, 122, 206));
        BtnCadastrar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        BtnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        BtnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Edit_1.png"))); // NOI18N
        BtnCadastrar.setText("Cadastrar Contrato");
        BtnCadastrar.setBorderPainted(false);
        BtnCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadastrarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Cadastro Contrato Financeiro");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Aqui é possível cadastrar os contratos, e registrá-los.");

        ValorTotalLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ValorTotalLabel.setForeground(new java.awt.Color(153, 153, 153));
        ValorTotalLabel.setText("Valor Total:");

        SituacaoComboLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SituacaoComboLabel.setForeground(new java.awt.Color(153, 153, 153));
        SituacaoComboLabel.setText("Situação:");

        BtnCancelar.setBackground(new java.awt.Color(30, 122, 206));
        BtnCancelar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        BtnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        BtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Close.png"))); // NOI18N
        BtnCancelar.setText("Cancelar");
        BtnCancelar.setBorderPainted(false);
        BtnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        BtnRetornar.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        BtnRetornar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/U Turn to Left_1.png"))); // NOI18N
        BtnRetornar.setText("Retornar");
        BtnRetornar.setAlignmentY(0.0F);
        BtnRetornar.setBorderPainted(false);
        BtnRetornar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnRetornar.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        BtnRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRetornarActionPerformed(evt);
            }
        });

        ValorTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        ValorTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValorTotalActionPerformed(evt);
            }
        });
        ValorTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ValorTotalKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ValorTotalKeyTyped(evt);
            }
        });

        ValorParcela.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        ValorParcela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValorParcelaActionPerformed(evt);
            }
        });
        ValorParcela.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ValorParcelaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ValorParcelaKeyTyped(evt);
            }
        });

        ValorParcelaLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ValorParcelaLabel.setForeground(new java.awt.Color(153, 153, 153));
        ValorParcelaLabel.setText("Valor Parcela:");

        NParcelas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        NParcelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NParcelasActionPerformed(evt);
            }
        });
        NParcelas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NParcelasKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NParcelasKeyTyped(evt);
            }
        });

        NParcelasLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NParcelasLabel.setForeground(new java.awt.Color(153, 153, 153));
        NParcelasLabel.setText("N° Parcelas:");

        nomeClienteFinanceiro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        nomeClienteFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeClienteFinanceiroActionPerformed(evt);
            }
        });
        nomeClienteFinanceiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nomeClienteFinanceiroKeyPressed(evt);
            }
        });

        NomeLocadorLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NomeLocadorLabel.setForeground(new java.awt.Color(153, 153, 153));
        NomeLocadorLabel.setText("Nome Cliente:");

        NomeContratoLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NomeContratoLabel1.setForeground(new java.awt.Color(153, 153, 153));
        NomeContratoLabel1.setText("Nome Contrato");

        NomeContrato.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        NomeContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeContratoActionPerformed(evt);
            }
        });
        NomeContrato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NomeContratoKeyPressed(evt);
            }
        });

        IdImovelLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        IdImovelLabel1.setForeground(new java.awt.Color(153, 153, 153));
        IdImovelLabel1.setText("Nome imovel");

        nomeImovelFinanceiro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        nomeImovelFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeImovelFinanceiroActionPerformed(evt);
            }
        });
        nomeImovelFinanceiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nomeImovelFinanceiroKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nomeImovelFinanceiroKeyTyped(evt);
            }
        });

        situacaoComboFinanceiro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular", "Pendente", "Atrasado" }));
        situacaoComboFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                situacaoComboFinanceiroActionPerformed(evt);
            }
        });

        tableImoveis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID Imovel", "Imovel"
            }
        ));
        jScrollPane1.setViewportView(tableImoveis);
        if (tableImoveis.getColumnModel().getColumnCount() > 0) {
            tableImoveis.getColumnModel().getColumn(0).setResizable(false);
            tableImoveis.getColumnModel().getColumn(0).setPreferredWidth(5);
        }

        tableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID Cliente", "Cliente"
            }
        ));
        jScrollPane2.setViewportView(tableClientes);
        if (tableClientes.getColumnModel().getColumnCount() > 0) {
            tableClientes.getColumnModel().getColumn(0).setResizable(false);
            tableClientes.getColumnModel().getColumn(0).setPreferredWidth(5);
        }

        BtnCadastrar1.setBackground(new java.awt.Color(30, 122, 206));
        BtnCadastrar1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        BtnCadastrar1.setForeground(new java.awt.Color(255, 255, 255));
        BtnCadastrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Search.png"))); // NOI18N
        BtnCadastrar1.setBorderPainted(false);
        BtnCadastrar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnCadastrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadastrar1ActionPerformed(evt);
            }
        });

        BtnProcurarCliente.setBackground(new java.awt.Color(30, 122, 206));
        BtnProcurarCliente.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        BtnProcurarCliente.setForeground(new java.awt.Color(255, 255, 255));
        BtnProcurarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Search.png"))); // NOI18N
        BtnProcurarCliente.setBorderPainted(false);
        BtnProcurarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnProcurarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProcurarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(NomeContratoLabel1)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(NomeContrato, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ValorParcelaLabel))
                                        .addComponent(ValorParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(NParcelasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(BtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(ValorTotalLabel)
                                                .addComponent(NParcelas, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                                .addComponent(ValorTotal))))))
                            .addComponent(situacaoComboFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SituacaoComboLabel)
                            .addComponent(BtnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NomeLocadorLabel)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(IdImovelLabel1)
                                    .addComponent(nomeImovelFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(BtnCadastrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(nomeClienteFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnProcurarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(BtnRetornar))
                .addContainerGap(302, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(BtnRetornar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(25, 25, 25)
                        .addComponent(IdImovelLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeImovelFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BtnCadastrar1))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NParcelasLabel)
                            .addComponent(NomeContratoLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NomeContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ValorTotalLabel)
                            .addComponent(ValorParcelaLabel)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ValorParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NomeLocadorLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeClienteFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BtnProcurarCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(SituacaoComboLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(situacaoComboFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(261, 261, 261))
        );

        javax.swing.GroupLayout PainelCentralLayout = new javax.swing.GroupLayout(PainelCentral);
        PainelCentral.setLayout(PainelCentralLayout);
        PainelCentralLayout.setHorizontalGroup(
            PainelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCentralLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(PainelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PainelCentralLayout.setVerticalGroup(
            PainelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCentralLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 997, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PainelCentral, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 934, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PainelCentral, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRetornarActionPerformed
        // TODO add your handling code here:
        Financeiro FinanceiroPrincipal = new Financeiro();
        ShowPanel(FinanceiroPrincipal);
    }//GEN-LAST:event_BtnRetornarActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        // TODO add your handling code here:
        String[] options = {"Sim", "Cancelar"};
        int resposta = JOptionPane.showOptionDialog(
                this,
                "Esta ação apagará todos os campos, tem certeza?",
                "Confirmação",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.WARNING_MESSAGE,
                null,
                options,
                options[0]
        );
        if (resposta == 0) {

        } else {
            BtnCancelar.requestFocus();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void BtnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadastrarActionPerformed
        // TODO add your handling code here:
        try {
            int selectedRowCliente = tableClientes.getSelectedRow();
            int selectedRowImovel = tableImoveis.getSelectedRow();
            
            if (selectedRowCliente == -1) {
                JOptionPane.showMessageDialog(null, "Por favor, selecione um cliente na tabela de clientes.");
                return;
            }
            if (selectedRowImovel == -1) {
                JOptionPane.showMessageDialog(null, "Por favor, selecione um imóvel na tabela de imóveis.");
                return;
            }
            
            String locador = tableClientes.getValueAt(selectedRowCliente, 0).toString(); 
            int idImovel = Integer.parseInt(tableImoveis.getValueAt(selectedRowImovel, 0).toString());

            String nomeContrato = NomeContrato.getText();
            String situacaoTexto = situacaoComboFinanceiro.getSelectedItem().toString();
            String valorParcela = ValorParcela.getText();
            String numeroParcelas = NParcelas.getText();
            String valorTotal = ValorTotal.getText();
            
            FinanceiroModel financeiro = new FinanceiroModel(
                    nomeContrato, situacaoTexto, valorParcela, numeroParcelas, valorTotal, locador, idImovel
            );
            
            JBDCCadastroFinanceiro dao = new JBDCCadastroFinanceiro();
            dao.inserirContratoFinanceiro(financeiro);
            
            JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!");
            
            limparCamposCadastro();
        } catch (Exception ex) {
            
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar: " + ex.getMessage());
        }
    }//GEN-LAST:event_BtnCadastrarActionPerformed

    private void ValorTotalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ValorTotalKeyPressed
        // TODO add your handling code here:
        if (evt.getExtendedKeyCode() == evt.VK_ENTER) {
            nomeClienteFinanceiro.requestFocus();
        }
    }//GEN-LAST:event_ValorTotalKeyPressed

    private void ValorTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ValorTotalKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_ValorTotalKeyTyped

    private void ValorTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValorTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValorTotalActionPerformed

    private void ValorParcelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValorParcelaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValorParcelaActionPerformed

    private void ValorParcelaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ValorParcelaKeyPressed
        // TODO add your handling code here:
        if (evt.getExtendedKeyCode() == evt.VK_ENTER) {
            NParcelas.requestFocus();
        }
    }//GEN-LAST:event_ValorParcelaKeyPressed

    private void ValorParcelaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ValorParcelaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_ValorParcelaKeyTyped

    private void NParcelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NParcelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NParcelasActionPerformed

    private void NParcelasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NParcelasKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_NParcelasKeyPressed

    private void NParcelasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NParcelasKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_NParcelasKeyTyped

    private void nomeClienteFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeClienteFinanceiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeClienteFinanceiroActionPerformed

    private void nomeClienteFinanceiroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeClienteFinanceiroKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeClienteFinanceiroKeyPressed

    private void NomeContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeContratoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeContratoActionPerformed

    private void NomeContratoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NomeContratoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeContratoKeyPressed

    private void nomeImovelFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeImovelFinanceiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeImovelFinanceiroActionPerformed

    private void nomeImovelFinanceiroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeImovelFinanceiroKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeImovelFinanceiroKeyPressed

    private void nomeImovelFinanceiroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeImovelFinanceiroKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeImovelFinanceiroKeyTyped

    private void situacaoComboFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_situacaoComboFinanceiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_situacaoComboFinanceiroActionPerformed

    private void BtnCadastrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadastrar1ActionPerformed

        String valorPesquisa = nomeImovelFinanceiro.getText();

        JBDCCadastroFinanceiro dao = new JBDCCadastroFinanceiro();

        ArrayList<FinanceiroModel> produtosFiltrados = dao.filtrarImoveisPorNome(valorPesquisa);

        entregaDadosPesquisado(produtosFiltrados);        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCadastrar1ActionPerformed

    private void BtnProcurarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProcurarClienteActionPerformed

        String valorPesquisa = nomeClienteFinanceiro.getText();

        JBDCCadastroFinanceiro dao = new JBDCCadastroFinanceiro();

        ArrayList<FinanceiroModel> produtosFiltrados = dao.filtrarClientesPorNome(valorPesquisa);

        entregaClientePesquisado(produtosFiltrados);
// TODO add your handling code here:
    }//GEN-LAST:event_BtnProcurarClienteActionPerformed

    private void ShowPanel(JPanel p) {
        p.setSize(799, 700);
        p.setLocation(0, 0);

        PainelCentral.removeAll();
        PainelCentral.add(p, BorderLayout.CENTER);
        PainelCentral.revalidate();
        PainelCentral.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCadastrar;
    private javax.swing.JButton BtnCadastrar1;
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnProcurarCliente;
    private javax.swing.JButton BtnRetornar;
    private javax.swing.JLabel IdImovelLabel1;
    private javax.swing.JTextField NParcelas;
    private javax.swing.JLabel NParcelasLabel;
    private javax.swing.JTextField NomeContrato;
    private javax.swing.JLabel NomeContratoLabel1;
    private javax.swing.JLabel NomeLocadorLabel;
    private javax.swing.JPanel PainelCentral;
    private javax.swing.JLabel SituacaoComboLabel;
    private javax.swing.JTextField ValorParcela;
    private javax.swing.JLabel ValorParcelaLabel;
    private javax.swing.JTextField ValorTotal;
    private javax.swing.JLabel ValorTotalLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nomeClienteFinanceiro;
    private javax.swing.JTextField nomeImovelFinanceiro;
    private javax.swing.JComboBox<String> situacaoComboFinanceiro;
    private javax.swing.JTable tableClientes;
    private javax.swing.JTable tableImoveis;
    // End of variables declaration//GEN-END:variables
}
