/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Imóvel;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.plaf.basic.BasicButtonUI;
import Imóvel.Imovel;
import javax.swing.JOptionPane;

/**
 *
 * @author pedro
 */
public class EditarExcluirImóvel extends javax.swing.JPanel {

    /**
     * Creates new form CadastroImovel
     */
    public EditarExcluirImóvel() {
        initComponents();
        JButton [] btns = {BtnCadastrar, BtnCancelar,BtnRetornar,BtnExcluir};
       for(JButton btn : btns){
           btn.setBackground(new Color(30,122,206));
           btn.setUI(new BasicButtonUI());
           BtnRetornar.setBackground(Color.WHITE);
           BtnExcluir.setBackground(new Color(255,98,98));
           btn.addMouseListener(new MouseListener(){
               @Override
               public void mouseClicked(MouseEvent e){
                   
               }
               @Override
               public void mousePressed(MouseEvent e){
                   
               }
               @Override 
                public void mouseReleased(MouseEvent e){
                   
               }
               @Override
               public void mouseEntered(MouseEvent e){
                    btn.setBackground(new Color(47,141,227));
                    BtnRetornar.setBackground(Color.WHITE);
                    BtnExcluir.setBackground(new Color(255,136,136));
               }
               @Override
               public void mouseExited(MouseEvent e){
                   btn.setBackground(new Color(30,122,206));
                   BtnRetornar.setBackground(Color.WHITE);
                   BtnExcluir.setBackground(new Color(255,98,98));
               }
           
           });
           }
   
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelCentral = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        BtnCadastrar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        BtnExcluir = new javax.swing.JButton();
        NumeroRegistroLabel = new javax.swing.JLabel();
        LocatarioLabel = new javax.swing.JLabel();
        SituacaoComboLabel = new javax.swing.JLabel();
        Endereco = new javax.swing.JTextField();
        LocadorLabel = new javax.swing.JLabel();
        UF = new javax.swing.JTextField();
        NomeImovel = new javax.swing.JTextField();
        Bairro = new javax.swing.JTextField();
        NumeroRegistro = new javax.swing.JTextField();
        DescricaoText = new javax.swing.JScrollPane();
        DescricaoTextArea = new javax.swing.JTextArea();
        BairroLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Locatario = new javax.swing.JTextField();
        UFLabel = new javax.swing.JLabel();
        DescricaoTextLabel1 = new javax.swing.JLabel();
        EnderecoLabel = new javax.swing.JLabel();
        Preco = new javax.swing.JTextField();
        CEPLabel = new javax.swing.JLabel();
        Numero = new javax.swing.JTextField();
        PrecoLabel = new javax.swing.JLabel();
        SituacaoCombo = new javax.swing.JComboBox<>();
        BtnRetornar = new javax.swing.JButton();
        Locador = new javax.swing.JTextField();
        NumeroLabel = new javax.swing.JLabel();
        NomeImovelLabel = new javax.swing.JLabel();
        CEP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        PainelCentral.setBackground(new java.awt.Color(36, 114, 221));
        PainelCentral.setForeground(new java.awt.Color(255, 255, 255));
        PainelCentral.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("/Home/MenuImóveis/Editar");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Imobils, Sistema Imobiliário");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        BtnCadastrar.setBackground(new java.awt.Color(30, 122, 206));
        BtnCadastrar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        BtnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        BtnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Edit_1.png"))); // NOI18N
        BtnCadastrar.setText("Editar Imóvel");
        BtnCadastrar.setBorderPainted(false);
        BtnCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadastrarActionPerformed(evt);
            }
        });

        BtnCancelar.setBackground(new java.awt.Color(30, 122, 206));
        BtnCancelar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        BtnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        BtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Close.png"))); // NOI18N
        BtnCancelar.setText("Cancelar");
        BtnCancelar.setBorderPainted(false);
        BtnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        BtnExcluir.setBackground(new java.awt.Color(255, 98, 98));
        BtnExcluir.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        BtnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        BtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Delete.png"))); // NOI18N
        BtnExcluir.setText("Excluir Imóvel");
        BtnExcluir.setBorderPainted(false);
        BtnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcluirActionPerformed(evt);
            }
        });

        NumeroRegistroLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NumeroRegistroLabel.setText("Número Registro:");

        LocatarioLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LocatarioLabel.setText("Nome Locatário");

        SituacaoComboLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SituacaoComboLabel.setText("Situação:");

        Endereco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Endereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EnderecoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EnderecoKeyTyped(evt);
            }
        });

        LocadorLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LocadorLabel.setText("Nome Locador");

        UF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        UF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UFActionPerformed(evt);
            }
        });
        UF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UFKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UFKeyTyped(evt);
            }
        });

        NomeImovel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        NomeImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeImovelActionPerformed(evt);
            }
        });
        NomeImovel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NomeImovelKeyPressed(evt);
            }
        });

        Bairro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Bairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BairroKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BairroKeyTyped(evt);
            }
        });

        NumeroRegistro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        NumeroRegistro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NumeroRegistroKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NumeroRegistroKeyTyped(evt);
            }
        });

        DescricaoTextArea.setColumns(20);
        DescricaoTextArea.setRows(5);
        DescricaoTextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DescricaoTextAreaKeyPressed(evt);
            }
        });
        DescricaoText.setViewportView(DescricaoTextArea);

        BairroLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BairroLabel.setText("Bairro");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Aqui é possível editar e excluir o respectivo imóvel.");

        Locatario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Locatario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LocatarioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                LocatarioKeyTyped(evt);
            }
        });

        UFLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UFLabel.setText("UF");

        DescricaoTextLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DescricaoTextLabel1.setText("Descrição Imóvel:");

        EnderecoLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EnderecoLabel.setText("Endereço");

        Preco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Preco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecoActionPerformed(evt);
            }
        });
        Preco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PrecoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PrecoKeyTyped(evt);
            }
        });

        CEPLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CEPLabel.setText("CEP");

        Numero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroActionPerformed(evt);
            }
        });
        Numero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NumeroKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NumeroKeyTyped(evt);
            }
        });

        PrecoLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PrecoLabel.setText("Preço:");

        SituacaoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular", "Atrasado", "Pendente" }));

        BtnRetornar.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        BtnRetornar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/U Turn to Left_1.png"))); // NOI18N
        BtnRetornar.setText("Retornar");
        BtnRetornar.setAlignmentY(0.0F);
        BtnRetornar.setBorderPainted(false);
        BtnRetornar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnRetornar.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        BtnRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRetornarActionPerformed(evt);
            }
        });

        Locador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Locador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LocadorKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                LocadorKeyTyped(evt);
            }
        });

        NumeroLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NumeroLabel.setText("Número");

        NomeImovelLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NomeImovelLabel.setText("Nome Imóvel:");

        CEP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        CEP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CEPKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CEPKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Editar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(BtnRetornar)
                        .addGap(649, 649, 649))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DescricaoTextLabel1)
                                    .addComponent(DescricaoText, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(EnderecoLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(UFLabel)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(UF))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Preco, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PrecoLabel)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CEPLabel)
                                            .addComponent(CEP, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BairroLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(NumeroLabel)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(Numero)))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LocadorLabel)
                                    .addComponent(Locador, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LocatarioLabel)
                                    .addComponent(Locatario)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(NomeImovelLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(NomeImovel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(NumeroRegistroLabel)
                                            .addComponent(NumeroRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(SituacaoComboLabel)
                                            .addComponent(SituacaoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(BtnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(BtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(39, 39, 39))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(BtnRetornar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(NomeImovelLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NomeImovel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(SituacaoComboLabel)
                                .addGap(32, 32, 32))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(NumeroRegistroLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(NumeroRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SituacaoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(DescricaoTextLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DescricaoText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(BairroLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(CEPLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CEP, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(NumeroLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Numero, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(EnderecoLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(PrecoLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Preco, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(UFLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(UF, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LocadorLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Locador, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(LocatarioLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Locatario, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PainelCentralLayout = new javax.swing.GroupLayout(PainelCentral);
        PainelCentral.setLayout(PainelCentralLayout);
        PainelCentralLayout.setHorizontalGroup(
            PainelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCentralLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(PainelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PainelCentralLayout.setVerticalGroup(
            PainelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCentralLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 799, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PainelCentral, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 724, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PainelCentral, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadastrarActionPerformed
        // TODO add your handling code here:
     
        String[] options = {"Sim", "Não"};
        int resposta = JOptionPane.showOptionDialog(
            this, 
            "Edição Registrada!"+ "\n" +
                "Nome do Imóvel: " + NomeImovel.getText() + "\n" +
                "Descrição: " + DescricaoTextArea.getText() + "\n" +
                "Locador: " + Locador.getText() + "\n" +
                "Locatário: " + Locatario.getText() + "\n" +
                "NumeroRegistro: " + NumeroRegistro.getText() + "\n" +
                "CEP: " + CEP.getText() + "\n" +
                "Bairro: " + Bairro.getText() + "\n" +
                "Endereço: " + Endereco.getText() + "\n" +
                "Numero: " + Numero.getText() + "\n" +
                "UF: " + UF.getText() + "\n" +
                "Preço: " + Preco.getText() + "\n" +
                "Situação: " + SituacaoCombo.getSelectedItem() + "\n\n\n" +
                "Cadastrar novo Imóvel?" +"\n",
                "Confirmação de Cadastro",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.WARNING_MESSAGE,
            null,
            options,
            options[0]);
        if (resposta == 1) {
        }else{
            NomeImovel.setText("");
                Bairro.setText("");
                Endereco.setText("");
                Numero.setText("");
                UF.setText("");
                DescricaoTextArea.setText("");
                Locador.setText("");
                Locatario.setText("");
                NumeroRegistro.setText("");
                CEP.setText("");
                Preco.setText("");
                SituacaoCombo.setSelectedIndex(-1);
                NomeImovel.requestFocus();
        }
    }//GEN-LAST:event_BtnCadastrarActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        // TODO add your handling code here:
        String[] options = {"Sim", "Cancelar"};
        int resposta = JOptionPane.showOptionDialog(
        this,
        "Esta ação apagará todos os campos, tem certeza?",
        "Confirmação",
        JOptionPane.DEFAULT_OPTION,
        JOptionPane.WARNING_MESSAGE,
        null,
        options,
        options[0]
    );
    if (resposta == 0) {
        
    } else {
        BtnCancelar.requestFocus();
    }        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void BtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluirActionPerformed
        // TODO add your handling code here:
        String[] options = {"Sim", "Cancelar"};
        int resposta = JOptionPane.showOptionDialog(
        this,
        "Esta ação apagará O IMÓVEL, tem certeza?",
        "Confirmação",
        JOptionPane.DEFAULT_OPTION,
        JOptionPane.WARNING_MESSAGE,
        null,
        options,
        options[0]
    );
    if (resposta == 0) {
        
    } else {
        BtnCancelar.requestFocus();
    }
    }//GEN-LAST:event_BtnExcluirActionPerformed

    private void EnderecoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EnderecoKeyPressed
        // TODO add your handling code here:
        if(evt.getExtendedKeyCode() == evt.VK_ENTER){
            UF.requestFocus();
        }
    }//GEN-LAST:event_EnderecoKeyPressed

    private void EnderecoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EnderecoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_EnderecoKeyTyped

    private void UFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UFKeyPressed
        // TODO add your handling code here:
        if(evt.getExtendedKeyCode() == evt.VK_ENTER){
            Preco.requestFocus();
        }
    }//GEN-LAST:event_UFKeyPressed

    private void UFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UFKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_UFKeyTyped

    private void NomeImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeImovelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeImovelActionPerformed

    private void NomeImovelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NomeImovelKeyPressed
        // TODO add your handling code here:
        if(evt.getExtendedKeyCode() == evt.VK_ENTER){
            NumeroRegistro.requestFocus();
        }
    }//GEN-LAST:event_NomeImovelKeyPressed

    private void BairroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BairroKeyPressed
        // TODO add your handling code here:
        if(evt.getExtendedKeyCode() == evt.VK_ENTER){
            Numero.requestFocus();
        }
    }//GEN-LAST:event_BairroKeyPressed

    private void BairroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BairroKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_BairroKeyTyped

    private void NumeroRegistroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NumeroRegistroKeyPressed
        // TODO add your handling code here:
        if(evt.getExtendedKeyCode() == evt.VK_ENTER){
            DescricaoTextArea.requestFocus();
        }
    }//GEN-LAST:event_NumeroRegistroKeyPressed

    private void NumeroRegistroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NumeroRegistroKeyTyped
        // TODO add your handling code here:
        char keyPress = evt.getKeyChar();
        if(!Character.isDigit(keyPress)){
            evt.consume();
        }
    }//GEN-LAST:event_NumeroRegistroKeyTyped

    private void DescricaoTextAreaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DescricaoTextAreaKeyPressed
        // TODO add your handling code here:
        if(evt.getExtendedKeyCode() == evt.VK_ENTER){
            CEP.requestFocus();
        }
    }//GEN-LAST:event_DescricaoTextAreaKeyPressed

    private void LocatarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LocatarioKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_LocatarioKeyPressed

    private void LocatarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LocatarioKeyTyped
        // TODO add your handling code here:
        char keyPress = evt.getKeyChar();
        if(!Character.isAlphabetic(keyPress) && keyPress != ' '){
            evt.consume();
        }
    }//GEN-LAST:event_LocatarioKeyTyped

    private void PrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecoActionPerformed

    private void PrecoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PrecoKeyTyped
        // TODO add your handling code here:
        char keyPress = evt.getKeyChar();
        if(!Character.isDigit(keyPress) && keyPress != '.' && keyPress != ','){
            evt.consume();
        }
    }//GEN-LAST:event_PrecoKeyTyped

    private void NumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumeroActionPerformed

    private void NumeroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NumeroKeyPressed
        // TODO add your handling code here:
        if(evt.getExtendedKeyCode() == evt.VK_ENTER){
            Endereco.requestFocus();
        }
    }//GEN-LAST:event_NumeroKeyPressed

    private void NumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NumeroKeyTyped
        // TODO add your handling code here:
        char keyPress = evt.getKeyChar();
        if(!Character.isDigit(keyPress)){
            evt.consume();
        }
    }//GEN-LAST:event_NumeroKeyTyped

    private void BtnRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRetornarActionPerformed
        // TODO add your handling code here:
        Imovel Imovel = new Imovel();
        ShowPanel(Imovel);
    }//GEN-LAST:event_BtnRetornarActionPerformed

    private void LocadorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LocadorKeyPressed
        // TODO add your handling code here:
        if(evt.getExtendedKeyCode() == evt.VK_ENTER){
            Locatario.requestFocus();
        }
    }//GEN-LAST:event_LocadorKeyPressed

    private void LocadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LocadorKeyTyped
        // TODO add your handling code here:
        char keyPress = evt.getKeyChar();
        if(!Character.isAlphabetic(keyPress) && keyPress != ' '){
            evt.consume();
        }
    }//GEN-LAST:event_LocadorKeyTyped

    private void CEPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CEPKeyPressed
        // TODO add your handling code here:
        if(evt.getExtendedKeyCode() == evt.VK_ENTER){
            Bairro.requestFocus();
        }
    }//GEN-LAST:event_CEPKeyPressed

    private void CEPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CEPKeyTyped
        // TODO add your handling code here:
        char keyPress = evt.getKeyChar();
        if(!Character.isDigit(keyPress)){
            evt.consume();
        }
    }//GEN-LAST:event_CEPKeyTyped

    private void PrecoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PrecoKeyPressed
        // TODO add your handling code here:
        if(evt.getExtendedKeyCode() == evt.VK_ENTER){
            Locador.requestFocus();
        }
    }//GEN-LAST:event_PrecoKeyPressed

    private void UFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UFActionPerformed

    
    private void ShowPanel(JPanel p){
    p.setSize(799, 700);
    p.setLocation(0, 0);
    
    PainelCentral.removeAll();
    PainelCentral.add(p, BorderLayout.CENTER); 
    PainelCentral.revalidate();
    PainelCentral.repaint();    
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Bairro;
    private javax.swing.JLabel BairroLabel;
    private javax.swing.JButton BtnCadastrar;
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnExcluir;
    private javax.swing.JButton BtnRetornar;
    private javax.swing.JTextField CEP;
    private javax.swing.JLabel CEPLabel;
    private javax.swing.JScrollPane DescricaoText;
    private javax.swing.JTextArea DescricaoTextArea;
    private javax.swing.JLabel DescricaoTextLabel1;
    private javax.swing.JTextField Endereco;
    private javax.swing.JLabel EnderecoLabel;
    private javax.swing.JTextField Locador;
    private javax.swing.JLabel LocadorLabel;
    private javax.swing.JTextField Locatario;
    private javax.swing.JLabel LocatarioLabel;
    private javax.swing.JTextField NomeImovel;
    private javax.swing.JLabel NomeImovelLabel;
    private javax.swing.JTextField Numero;
    private javax.swing.JLabel NumeroLabel;
    private javax.swing.JTextField NumeroRegistro;
    private javax.swing.JLabel NumeroRegistroLabel;
    private javax.swing.JPanel PainelCentral;
    private javax.swing.JTextField Preco;
    private javax.swing.JLabel PrecoLabel;
    private javax.swing.JComboBox<String> SituacaoCombo;
    private javax.swing.JLabel SituacaoComboLabel;
    private javax.swing.JTextField UF;
    private javax.swing.JLabel UFLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
