/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Imóvel;

import DAO.JBDCCadastroImovel;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import TelaInicial.TelaInicial;
import javax.swing.JPanel;
import javax.swing.plaf.basic.BasicButtonUI;
import javax.swing.plaf.basic.BasicComboBoxUI;

import Imóvel.CadastroImovel;
import Imóvel.EditarExcluirImóvel;
import Model.CadastroImovelModel;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Imóvel.DetalharImovel;
import java.text.MessageFormat;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.print.attribute.standard.OrientationRequested;
import javax.swing.JTable;

/**
 *
 * @author pedro
 */



public class Imovel extends javax.swing.JPanel {

    /**
     * Creates new form CadastroImóvel
     */
  
    public Imovel() {
        initComponents();
        MostrarImoveisTabela();
        
        JButton [] btns = {BtnImovel, BtnPesquisa,BtnRecarregar,BtnDetalhar};
       for(JButton btn : btns){
           btn.setBackground(new Color(30,122,206));
           btn.setUI(new BasicButtonUI());
           btn.addMouseListener(new MouseListener(){
               @Override
               public void mouseClicked(MouseEvent e){
                   
               }
               @Override
               public void mousePressed(MouseEvent e){
                   
               }
               @Override 
                public void mouseReleased(MouseEvent e){
                   
               }
               @Override
               public void mouseEntered(MouseEvent e){
                    btn.setBackground(new Color(47,141,227));
               }
               @Override
               public void mouseExited(MouseEvent e){
                   btn.setBackground(new Color(30,122,206));
               }
           
           });
           }
       
           BtnEditar.setBackground(new Color(249,193,51));
           BtnEditar.setUI(new BasicButtonUI());
           BtnEditar.addMouseListener(new MouseListener(){
               @Override
               public void mouseClicked(MouseEvent e){
                   
               }
               @Override
               public void mousePressed(MouseEvent e){
                   
               }
               @Override 
                public void mouseReleased(MouseEvent e){
                   
               }
               @Override
               public void mouseEntered(MouseEvent e){
                   
                   BtnEditar.setBackground(new Color(255,197,52));
               }
               @Override
               public void mouseExited(MouseEvent e){
                   
                   BtnEditar.setBackground(new Color(249,193,51));
               }
           
           });
       
           BtnExcluir.setBackground(new Color(153,0,51));
           BtnExcluir.setUI(new BasicButtonUI());
           BtnExcluir.addMouseListener(new MouseListener(){
               @Override
               public void mouseClicked(MouseEvent e){
                   
               }
               @Override
               public void mousePressed(MouseEvent e){
                   
               }
               @Override 
                public void mouseReleased(MouseEvent e){
                   
               }
               @Override
               public void mouseEntered(MouseEvent e){
                   
                   BtnExcluir.setBackground(new Color(179,21,74));
               }
               @Override
               public void mouseExited(MouseEvent e){
                   
                   BtnExcluir.setBackground(new Color(153,0,51));
               }
           
           });
           
// Adiciona o SistemaContent ao novo JPanel ou à outra parte da interface
       
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelCentral = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        BtnImovel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaImovel = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        PesquisarText = new javax.swing.JTextField();
        FiltroCombo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        BtnPesquisa = new javax.swing.JButton();
        BtnEditar = new javax.swing.JButton();
        BtnExcluir = new javax.swing.JButton();
        BtnRecarregar = new javax.swing.JButton();
        BtnDetalhar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        PainelCentral.setBackground(new java.awt.Color(36, 114, 221));
        PainelCentral.setForeground(new java.awt.Color(255, 255, 255));
        PainelCentral.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("/Home/MenuImóveis");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Imobils, Sistema Imobiliário");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        BtnImovel.setBackground(new java.awt.Color(30, 122, 206));
        BtnImovel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        BtnImovel.setForeground(new java.awt.Color(255, 255, 255));
        BtnImovel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Terms and Conditions.png"))); // NOI18N
        BtnImovel.setText("Cadastrar Novo Imóvel");
        BtnImovel.setBorderPainted(false);
        BtnImovel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnImovelActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Menu de Imóveis");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Aqui é possível acessar e visualziar as opções para os imóveis");

        TabelaImovel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdImovel", "Nome", "Locador", "Locátario", "Preço", "CEP", "Situação"
            }
        ));
        TabelaImovel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaImovelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaImovel);
        if (TabelaImovel.getColumnModel().getColumnCount() > 0) {
            TabelaImovel.getColumnModel().getColumn(0).setResizable(false);
            TabelaImovel.getColumnModel().getColumn(1).setResizable(false);
            TabelaImovel.getColumnModel().getColumn(2).setResizable(false);
            TabelaImovel.getColumnModel().getColumn(3).setResizable(false);
            TabelaImovel.getColumnModel().getColumn(4).setResizable(false);
            TabelaImovel.getColumnModel().getColumn(5).setResizable(false);
            TabelaImovel.getColumnModel().getColumn(6).setResizable(false);
        }

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Pesquisar");

        PesquisarText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        PesquisarText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarTextActionPerformed(evt);
            }
        });

        FiltroCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IdImóvel", "Nome do Imóvel", "Locador", "Locatário", "CEP", "Preço", "Situação" }));
        FiltroCombo.setBorder(null);
        FiltroCombo.setLightWeightPopupEnabled(false);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Filtrar por:");

        BtnPesquisa.setBackground(new java.awt.Color(30, 122, 206));
        BtnPesquisa.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        BtnPesquisa.setForeground(new java.awt.Color(255, 255, 255));
        BtnPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Search.png"))); // NOI18N
        BtnPesquisa.setText("Pesquisar");
        BtnPesquisa.setBorderPainted(false);
        BtnPesquisa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPesquisaActionPerformed(evt);
            }
        });

        BtnEditar.setBackground(new java.awt.Color(249, 193, 51));
        BtnEditar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        BtnEditar.setForeground(new java.awt.Color(27, 27, 27));
        BtnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Edit_1.png"))); // NOI18N
        BtnEditar.setText("Editar Imóvel");
        BtnEditar.setBorderPainted(false);
        BtnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarActionPerformed(evt);
            }
        });

        BtnExcluir.setBackground(new java.awt.Color(153, 0, 51));
        BtnExcluir.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        BtnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        BtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Close.png"))); // NOI18N
        BtnExcluir.setText("Excluir Imóvel");
        BtnExcluir.setBorderPainted(false);
        BtnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcluirActionPerformed(evt);
            }
        });

        BtnRecarregar.setBackground(new java.awt.Color(30, 122, 206));
        BtnRecarregar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        BtnRecarregar.setForeground(new java.awt.Color(255, 255, 255));
        BtnRecarregar.setText("Recarregar");
        BtnRecarregar.setBorderPainted(false);
        BtnRecarregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnRecarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRecarregarActionPerformed(evt);
            }
        });

        BtnDetalhar.setBackground(new java.awt.Color(30, 122, 206));
        BtnDetalhar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        BtnDetalhar.setForeground(new java.awt.Color(255, 255, 255));
        BtnDetalhar.setText("Detalhar");
        BtnDetalhar.setBorderPainted(false);
        BtnDetalhar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnDetalhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDetalharActionPerformed(evt);
            }
        });

        jButton1.setText("Impressão Tabela");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(PesquisarText, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel5))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(FiltroCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addComponent(jButton1)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(BtnImovel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnRecarregar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnDetalhar, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)))
                .addGap(13, 13, 13))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnImovel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnRecarregar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnDetalhar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PesquisarText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FiltroCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(BtnPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout PainelCentralLayout = new javax.swing.GroupLayout(PainelCentral);
        PainelCentral.setLayout(PainelCentralLayout);
        PainelCentralLayout.setHorizontalGroup(
            PainelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCentralLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(PainelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(530, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PainelCentralLayout.setVerticalGroup(
            PainelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCentralLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 799, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PainelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 724, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PainelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnImovelActionPerformed
        // TODO add your handling code here:
        CadastroImovel CdImovel = new CadastroImovel();
        ShowPanel(CdImovel);
        
    }//GEN-LAST:event_BtnImovelActionPerformed

    private void PesquisarTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PesquisarTextActionPerformed

    private void BtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarActionPerformed
        // TODO add your handling code here:
        CadastroImovelModel ListadeImoveis = new CadastroImovelModel();
        JBDCCadastroImovel CadastroImovel = new JBDCCadastroImovel();
        int LinhaSelecionada = TabelaImovel.getSelectedRow();
        DefaultTableModel ModeloTabela = (DefaultTableModel) TabelaImovel.getModel();
        int ImovelSelecionado = CadastroImovel.MostrarListaImovel().get(LinhaSelecionada).getIdImovel();
        CadastroImovel.ConsultaImovel(ImovelSelecionado);
        
        EditarExcluirImóvel EditarImovel = new EditarExcluirImóvel();
        ShowPanel(EditarImovel);  
    }//GEN-LAST:event_BtnEditarActionPerformed

    private void BtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluirActionPerformed
        // TODO add your handling code here:
        CadastroImovelModel ListadeImoveis = new CadastroImovelModel();
        JBDCCadastroImovel CadastroImovel = new JBDCCadastroImovel();
        int LinhaSelecionada = TabelaImovel.getSelectedRow();
        DefaultTableModel ModeloTabela = (DefaultTableModel) TabelaImovel.getModel();
        int ImovelSelecionado = CadastroImovel.MostrarListaImovel().get(LinhaSelecionada).getIdImovel();
        String ImovelNome = CadastroImovel.MostrarListaImovel().get(LinhaSelecionada).getNomeImovel();
        String LocatarioImovel = CadastroImovel.MostrarListaImovel().get(LinhaSelecionada).getLocatario();
        
         String[] options = {"Sim", "Cancelar"};
         int resposta = JOptionPane.showOptionDialog(
            this,
            "Deseja excluir mesmo este imóvel?" + "\n\n"+
            "Id do Imóvel: " + ImovelSelecionado + "\n" +
            "Nome do Imóvel: " + ImovelNome+ "\n" +
            "Locatário: " + LocatarioImovel + "\n\n",
            "Confirmação",
            JOptionPane.DEFAULT_OPTION,
            JOptionPane.WARNING_MESSAGE,
            null,
            options,
            options[0]);
        if (resposta == 0) {
            ListadeImoveis.setIdImovel(ImovelSelecionado);
            CadastroImovel.ExcluirImovel(ListadeImoveis);
        } else {
            JOptionPane.showMessageDialog(null, "Operação Cancelada!");
        }
    }//GEN-LAST:event_BtnExcluirActionPerformed

    private void BtnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPesquisaActionPerformed
        // TODO add your handling code here:
        
        RecarregarImoveisTabela();
        JBDCCadastroImovel ListaDeImóveis = new JBDCCadastroImovel();
        CadastroImovelModel ListadoModel = new CadastroImovelModel();
        ListadoModel.setValorConsulta(FiltroCombo.getSelectedIndex());
        ListadoModel.setItemPesquisar(PesquisarText.getText());
         ArrayList<CadastroImovelModel> ListaImoveis = ListaDeImóveis.FiltrarImovel(ListadoModel);
         
        DefaultTableModel modelo = (DefaultTableModel) TabelaImovel.getModel();
        modelo.setRowCount(0);

    for (CadastroImovelModel Imovel : ListaImoveis) {
        modelo.addRow(new Object[] {
            Imovel.getIdImovel(),
            Imovel.getNomeImovel(),
            Imovel.getLocador(),
            Imovel.getLocatario(),
            Imovel.getValorPreco(),
            Imovel.getCepImovel(),
            Imovel.getSituacao()
        });
    }
    }//GEN-LAST:event_BtnPesquisaActionPerformed

    private void TabelaImovelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaImovelMouseClicked
        // TODO add your handling code here:
        CadastroImovelModel ListadeImoveis = new CadastroImovelModel();
        
    }//GEN-LAST:event_TabelaImovelMouseClicked

    private void BtnRecarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRecarregarActionPerformed
        // TODO add your handling code here:
        RecarregarImoveisTabela();
    }//GEN-LAST:event_BtnRecarregarActionPerformed

    private void BtnDetalharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDetalharActionPerformed
        // TODO add your handling code here    
        CadastroImovelModel ListadeImoveis = new CadastroImovelModel();
        JBDCCadastroImovel CadastroImovel = new JBDCCadastroImovel();
        int LinhaSelecionada = TabelaImovel.getSelectedRow();
        DefaultTableModel ModeloTabela = (DefaultTableModel) TabelaImovel.getModel();
        int ImovelSelecionado = CadastroImovel.MostrarListaImovel().get(LinhaSelecionada).getIdImovel();
        CadastroImovel.ConsultaImovel(ImovelSelecionado);
        
        DetalharImovel DetalhesImóvel = new DetalharImovel();
        DetalhesImóvel.setVisible(true);
    }//GEN-LAST:event_BtnDetalharActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Imobills Sistema Imobiliário");
        MessageFormat footer = new MessageFormat("Página(0,number,integer)");
        try{
            PrintRequestAttributeSet set = new HashPrintRequestAttributeSet();
            set.add(OrientationRequested.LANDSCAPE);
            TabelaImovel.print(JTable.PrintMode.FIT_WIDTH, header, footer, true,set,true);
            JOptionPane.showMessageDialog(null, "Impressão Concluida!");
        }catch(java.awt.print.PrinterException e){
            JOptionPane.showMessageDialog(null, "Falha");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


     private void ShowPanel(JPanel p){
    p.setSize(799, 700);
    p.setLocation(0, 0);
    
    PainelCentral.removeAll();
    PainelCentral.add(p, BorderLayout.CENTER); 
    PainelCentral.revalidate();
    PainelCentral.repaint();    
}
   
     public void MostrarImoveisTabela(){
        JBDCCadastroImovel ListaImovel = new JBDCCadastroImovel();
        ArrayList<CadastroImovelModel> listaimovelcoluna =  ListaImovel.MostrarListaImovel();
        
        
        DefaultTableModel model = (DefaultTableModel)TabelaImovel.getModel();
         model.setRowCount(0);
         model.setColumnCount(7);
        
        Object[] row = new Object[7];
        for(int i = 0;i < listaimovelcoluna.size();i++){
            row[0] = listaimovelcoluna.get(i).getIdImovel();
            row[1] = listaimovelcoluna.get(i).getNomeImovel();
            row[2] = listaimovelcoluna.get(i).getLocador();
            row[3] = listaimovelcoluna.get(i).getLocatario();
            row[4] = listaimovelcoluna.get(i).getValorPreco();
            row[5] = listaimovelcoluna.get(i).getCepImovel();
            row[6] = listaimovelcoluna.get(i).getSituacao();
            

            model.addRow(row.clone());

        }
       
    }
     
     public void RecarregarImoveisTabela() {
    DefaultTableModel model = (DefaultTableModel) TabelaImovel.getModel();
    model.setRowCount(0);
    model.setColumnCount(7);
    MostrarImoveisTabela();
}
     
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDetalhar;
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnExcluir;
    private javax.swing.JButton BtnImovel;
    private javax.swing.JButton BtnPesquisa;
    private javax.swing.JButton BtnRecarregar;
    private javax.swing.JComboBox<String> FiltroCombo;
    private javax.swing.JPanel PainelCentral;
    private javax.swing.JTextField PesquisarText;
    private javax.swing.JTable TabelaImovel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
