/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TelaInicial;

import Clientes.ClientesPrincipal;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.plaf.basic.BasicButtonUI;
import Imóvel.Imovel;
import java.awt.BorderLayout;
import javax.swing.JPanel;


import TelaInicial.TelaBoasVindas;
import Financeiro.Financeiro;
import Contrato.Contrato;
import DashBoard.DashBoard;
/**
 *
 * @author pedro
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
       JButton [] btns = {BtnPrincipal,BtnImovel,BtnClientes,BtnContrato,BtnFinanceiro,Dashbtn};
       for(JButton btn : btns){
           btn.setBackground(new Color(30,122,206));
           btn.setUI(new BasicButtonUI());
           btn.addMouseListener(new MouseListener(){
               @Override
               public void mouseClicked(MouseEvent e){
                   
               }
               @Override
               public void mousePressed(MouseEvent e){
                   
               }
               @Override 
                public void mouseReleased(MouseEvent e){
                   
               }
               @Override
               public void mouseEntered(MouseEvent e){
                    btn.setBackground(new Color(47,141,227));
               }
               @Override
               public void mouseExited(MouseEvent e){
                   btn.setBackground(new Color(30,122,206));
               }
           
           });
           }
       
       TelaBoasVindas principal = new TelaBoasVindas();
        ShowPanel(principal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Separator = new javax.swing.JLabel();
        BtnPrincipal = new javax.swing.JButton();
        BtnImovel = new javax.swing.JButton();
        BtnClientes = new javax.swing.JButton();
        BtnContrato = new javax.swing.JButton();
        BtnFinanceiro = new javax.swing.JButton();
        Titulo1 = new javax.swing.JLabel();
        Dashbtn = new javax.swing.JButton();
        SistemaContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(11, 83, 182));

        Titulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Imobills");
        Titulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Separator.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Separator.setForeground(new java.awt.Color(255, 255, 255));
        Separator.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Separator.setText("Sistema Imobiliário");
        Separator.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        BtnPrincipal.setBackground(new java.awt.Color(30, 122, 206));
        BtnPrincipal.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        BtnPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        BtnPrincipal.setText("Principal");
        BtnPrincipal.setBorderPainted(false);
        BtnPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrincipalActionPerformed(evt);
            }
        });

        BtnImovel.setBackground(new java.awt.Color(30, 122, 206));
        BtnImovel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        BtnImovel.setForeground(new java.awt.Color(255, 255, 255));
        BtnImovel.setText("Imóvel");
        BtnImovel.setBorderPainted(false);
        BtnImovel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnImovelActionPerformed(evt);
            }
        });

        BtnClientes.setBackground(new java.awt.Color(30, 122, 206));
        BtnClientes.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        BtnClientes.setForeground(new java.awt.Color(255, 255, 255));
        BtnClientes.setText("Clientes");
        BtnClientes.setBorderPainted(false);
        BtnClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClientesActionPerformed(evt);
            }
        });

        BtnContrato.setBackground(new java.awt.Color(30, 122, 206));
        BtnContrato.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        BtnContrato.setForeground(new java.awt.Color(255, 255, 255));
        BtnContrato.setText("Contratos");
        BtnContrato.setBorderPainted(false);
        BtnContrato.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnContratoActionPerformed(evt);
            }
        });

        BtnFinanceiro.setBackground(new java.awt.Color(30, 122, 206));
        BtnFinanceiro.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        BtnFinanceiro.setForeground(new java.awt.Color(255, 255, 255));
        BtnFinanceiro.setText("Financeiro");
        BtnFinanceiro.setBorderPainted(false);
        BtnFinanceiro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnFinanceiro.setDoubleBuffered(true);
        BtnFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFinanceiroActionPerformed(evt);
            }
        });

        Titulo1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Titulo1.setForeground(new java.awt.Color(255, 255, 255));
        Titulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo1.setText("Funções");
        Titulo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Dashbtn.setBackground(new java.awt.Color(30, 122, 206));
        Dashbtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        Dashbtn.setForeground(new java.awt.Color(255, 255, 255));
        Dashbtn.setText("DashBoard");
        Dashbtn.setBorderPainted(false);
        Dashbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Dashbtn.setDoubleBuffered(true);
        Dashbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DashbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Titulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtnPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Separator, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
            .addComponent(BtnImovel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtnClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtnContrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtnFinanceiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Titulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Dashbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Separator, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(BtnPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnImovel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Dashbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout SistemaContentLayout = new javax.swing.GroupLayout(SistemaContent);
        SistemaContent.setLayout(SistemaContentLayout);
        SistemaContentLayout.setHorizontalGroup(
            SistemaContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 799, Short.MAX_VALUE)
        );
        SistemaContentLayout.setVerticalGroup(
            SistemaContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(SistemaContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SistemaContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrincipalActionPerformed
        // TODO add your handling code here:
        TelaBoasVindas principal = new TelaBoasVindas();
        ShowPanel(principal);
    }//GEN-LAST:event_BtnPrincipalActionPerformed

    private void BtnImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnImovelActionPerformed
        // TODO add your handling code here:
        Imovel ImovelPrincipal = new Imovel();
        ShowPanel(ImovelPrincipal);
    }//GEN-LAST:event_BtnImovelActionPerformed

    private void BtnFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFinanceiroActionPerformed
        // TODO add your handling code here:
        Financeiro FinanceiroPrincipal = new Financeiro();
        ShowPanel(FinanceiroPrincipal);
    }//GEN-LAST:event_BtnFinanceiroActionPerformed

    private void BtnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClientesActionPerformed
        // TODO add your handling code here:
        ClientesPrincipal ClientesPrincipal = new ClientesPrincipal();
        ShowPanel(ClientesPrincipal);
    }//GEN-LAST:event_BtnClientesActionPerformed

    private void BtnContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnContratoActionPerformed
        // TODO add your handling code here:
        Contrato ContratoPrincipal = new Contrato();
        ShowPanel(ContratoPrincipal);
    }//GEN-LAST:event_BtnContratoActionPerformed

    private void DashbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashbtnActionPerformed
        DashBoard dashboard = new DashBoard();
        ShowPanel (dashboard);        // TODO add your handling code here:
    }//GEN-LAST:event_DashbtnActionPerformed


    /**
     * @param args the command line arguments
     */
    
    private void ShowPanel(JPanel p){
        p.setSize(799, 700);
        p.setLocation(0,0);
        
        SistemaContent.removeAll();
        SistemaContent.add(p, BorderLayout.CENTER);
        SistemaContent.revalidate();
        SistemaContent.repaint();
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }
    
  public JPanel getSistemaContent() {
    return SistemaContent;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnClientes;
    private javax.swing.JButton BtnContrato;
    private javax.swing.JButton BtnFinanceiro;
    private javax.swing.JButton BtnImovel;
    private javax.swing.JButton BtnPrincipal;
    private javax.swing.JButton Dashbtn;
    private javax.swing.JLabel Separator;
    private javax.swing.JPanel SistemaContent;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel Titulo1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
